### ISSUE TITLE
求一个裸的js的版本

### ISSUE THREAD

**Issue by Ehco1996** [QiShaoXuan/vuepress-plugin-cat#1]

**Comment by minza** [comment]
想看怎么实现的

**Comment by QiShaoXuan** [comment]
可以看下 https://github.com/QiShaoXuan/live2DModel，但是源码都是压缩过的

**Comment by QiShaoXuan** [comment]
可以看下 [live2DModel](https://github.com/QiShaoXuan/live2DModel)，但是源码都是压缩过的
