### ISSUE TITLE
猫咪怎么用呢？

### ISSUE THREAD

**Issue by cangyu1993** [QiShaoXuan/vuepress-plugin-cat#3]
没找到放置猫咪的demo，能指个路吗？

**Comment by cangyu1993** [comment]
![image](https://user-images.githubusercontent.com/42930030/63334282-ac3c5f00-c36d-11e9-84c7-f73e3c892912.png)
ok,搞定了

**Comment by QiuYeDx** [comment]
不知道怎么用这个版本的……之前在网上找的api复制粘贴代码就能用了，就是猫猫的背景不是透明的，有层白块5555
求救！怎么在wordpress博客的首页用这个项目的方法呀～config.js是什么文件啊，没看到有这个文件

**Comment by QiuYeDx** [comment]
> ![image](https://user-images.githubusercontent.com/42930030/63334282-ac3c5f00-c36d-11e9-84c7-f73e3c892912.png)
> ok,搞定了

**Comment by QiuYeDx** [comment]
> ![image](https://user-images.githubusercontent.com/42930030/63334282-ac3c5f00-c36d-11e9-84c7-f73e3c892912.png)
> ok,搞定了

不知道怎么用这个版本的……之前在网上找的api复制粘贴代码就能用了，就是猫猫的背景不是透明的，有层白块5555
求救！怎么在wordpress博客的首页用这个项目的方法呀～config.js是什么文件啊，没看到有这个文件

**Comment by cangyu1993** [comment]
这个插件有api介绍，去看看官方文档应该够了，再不行可以自己写样式覆盖
